# Generated by Django 5.1.7 on 2025-03-21 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boutique', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('upi_transaction_id', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_screenshot', models.ImageField(blank=True, null=True, upload_to='payments/')),
                ('status', models.CharField(choices=[('pending', 'Pending Payment'), ('paid', 'Payment Confirmed'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boutique.product')),
            ],
        ),
    ]
